<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="LAPTOP-1PH6218O" failures="1" tests="3" name="Test" time="87.477" errors="0" timestamp="2024-01-18T15:13:01 IST">
  <testcase classname="com.Test.Test1_HomePageNavigation" name="verify_HomePageNavigation" time="6.594"/>
  <testcase classname="com.Test.Test11_ContactUs" name="VerifyContactUs" time="5.39">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [1Contact Us] but found [Contact Us]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [1Contact Us] but found [Contact Us]
at com.Test.Test11_ContactUs.VerifyContactUs(Test11_ContactUs.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- VerifyContactUs -->
  <testcase classname="com.Test.Test3_CardSection" name="VerifyCardSection" time="0.002"/>
  <testcase classname="com.Utility.BaseClass" name="@BeforeSuite BS" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite BS -->
  <testcase classname="com.Utility.BaseClass" name="@BeforeSuite BS" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite BS -->
</testsuite> <!-- Test -->
